### ISSUE TITLE
Age and Geo infomation

### ISSUE THREAD

**Issue by Kevin063** [IncentWang/TiktokInfoGetter#2]
Hi, could we also get the users' age and geo info through the API? They are visible to the public in some other scrapers like this https://hypeauditor.com/.

**Comment by IncentWang** [comment]
From what I know, there is no way to get users' age information. For Geo info, I assume the common approach is to fetch information on users' latest uploaded video to use the geo-information on that video as "user's geoinformation". We can fetch those info but it may need much more computing resources and internet resources than we are having now. We need to apply a proxy server on requests first to avoid Tiktok banning us, then we can try to add this feature.
